apiVersion: apps/v1
kind: Deployment
metadata:
  name: user01-gateway-test2
  namespace: hotelone
  labels:
    app: user01-gateway-test2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user01-gateway-test2
  template:
    metadata:
      labels:
        app: user01-gateway-test2
    spec:
      containers:
        - name: user01-gateway-test2
          image: 496278789073.dkr.ecr.ap-northeast-2.amazonaws.com/teamtwohotel2-gateway:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
