apiVersion: v1
kind: Service
metadata:
  name: user01-gateway-test2
  namespace: hotelone
  labels:
    app: user01-gateway-test2
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: user01-gateway-test2
